### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by chenfan9** [chenfan9/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://chenfan9.github.io/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file
- [x] There are no linting errors in your JavaScript (this will also be expected for all future projects)

**Comment by chenfan9** [comment]
js project

**Comment by KatieMFritz** [comment]
Nice work, Fan! :fire: Your app works exactly as it should. 😁 

You also did a wonderful job with naming your variables. It's easy to understand what each variable is, and you nailed the camelCase. 🐫 ✨ 

### Reduce duplicate code

When I look at your `updatePreview` function and your `updateHtml` function, I see that they are almost identical. The only real difference is between `previewParagraph.innerHTML` and `htmlParagraph.textContent`. 

#### Part 1: Use variables to reduce duplicate strings

Since you're assigning the exact same HTML string twice (the actual profile code, from `<h1>` to `.</p>`) , what would you think about assigning it to a variable first, then reusing it when you update the page? So for example, if I'm doing this:

``` js
element1.textContent = 'hello' + yourName
element2.innerHTML = 'hello' + yourName
```

Then whenever I want to update `'hello' + yourName`, I have to do it in two places. We're not only too lazy for that 😄, but it can also cause bugs (especially if `'hello' + yourName` is a longer, more complex string). If we update one string and forget to update the other the same way, then we have an inconsistency. A solution for this would be to move `'hello' + yourName` to a variable, like this:

``` js
var greeting = 'hello' + yourName

element1.textContent = greeting
element2.innerHTML = greeting
```

Now whenever we want to update the greeting, we can do it in just one place. Future development is now much easier and it's more difficult to create bugs. Does that make sense?

#### Part 2: Combine functions

Since `updatePreview` and `updateHtml` use all the same variables (including your new one with the profile content) and should always happen at the same time (when a user types anything), you can combine them into one function that does 2 things.

In our greeting example above, instead of doing something like this:
``` js
var greetUser1 = function() {
  var greeting = 'hello' + yourName

  element1.textContent = greeting
}

var greetUser2 = function() {
  var greeting = 'hello' + yourName

  element2.innerHTML = greeting
}
```
we could do this:
``` js
var greetUser = function() {
  var greeting = 'hello' + yourName

  element1.textContent = greeting
  element2.innerHTML = greeting
}
```
This way, if you want to change the `greeting` variable, you only have to do it once, and also you only have to have one set of event listeners.

* * *
Does that make sense? Feel free to message me on Slack if you have any questions or would like a different example!

Otherwise, make your changes and comment back here when you're done. 😸

**Comment by chenfan9** [comment]
updated

**Comment by KatieMFritz** [comment]
That looks AWESOME. Great job improving this over several rounds! 🔥 💥 🌴 😁 

:shipit:
